---
- name: Ensure Windows service is running
  hosts: windows
  tasks:
    - name: Check if the service is running
      ansible.windows.win_service:
        name: 'W3SVC'
      register: service_status

    - name: Debug service status
      ansible.builtin.debug:
        var: service_status

    - name: Start the service if it is not running
      ansible.windows.win_service:
        name: 'W3SVC'
        state: started
      when: service_status.state != 'running'
      register: service_log

    - name: Log service status when started
      local_action:
        module: lineinfile
        path: /home/Redhat/status.log
        line: "{{ ansible_date_time.iso8601 }} IIS service is {{ service_log.state }}"
        insertafter: '^.*$'
      when: service_status.state != 'running'      

    - name: Log service status when already running
      local_action:
        module: lineinfile
        path: /home/Redhat/status.log
        line: "{{ ansible_date_time.iso8601 }} IIS service is already running"
        insertafter: '^.*$'
      when: service_status.state == 'running'

   

      