---
- name: Copy content of multiple log files from Windows to Linux
  hosts: windows
  tasks:
    - name: Define log files to copy
      set_fact:
        log_files:
          - C:/ansiblelogs/logfile.txt
          - C:/ansiblelogs/logfile1.txt

    - name: Read the content of log files
      ansible.builtin.win_shell: Get-Content {{ item }}
      register: log_content
      loop: "{{ log_files }}"
      loop_control:
        label: "{{ item }}"

    - name: Debug service status
      ansible.builtin.debug:
        var: log_content

    - name: Show stdout_lines
      ansible.builtin.debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ log_content.results }}"

    - name: Create a directory on localhost
      ansible.builtin.file:
        path: /home/Redhat/Log
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Create a file inside the directory on localhost
      ansible.builtin.file:
        path: /home/Redhat/Log/{{ item | basename }}
        state: touch
        mode: '0644'
      loop: "{{ log_files }}"
      delegate_to: localhost

    - name: Log service status when already running on localhost 
      ansible.builtin.lineinfile:
        path: "/home/Redhat/Log/{{ item.item | basename }}"
        #line: "{{ ansible_date_time.iso8601 }} {{ item.item }} content: {{ item.stdout_lines | join('\n') }}"
        line: "{{ ansible_date_time.iso8601 }} {{ item.stdout_lines | join('\n') }}"
      loop: "{{ log_content.results }}"
      delegate_to: localhost
