---
- name: Ensure Windows services are running and copy log content
  hosts: windows
  tasks:
    - name: Define services to check.
      set_fact:
        services:
          - BTAGService
          - Appinfo

    - name: Check if the services are running
      ansible.windows.win_service:
        name: "{{ item }}"
      register: service_status
      loop: "{{ services }}"
      loop_control:
        label: "{{ item }}"

    - name: Create a directory on localhost
      ansible.builtin.file:
        path: /home/Redhat/Log
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Create a file for each service inside the directory on localhost
      ansible.builtin.file:
        path: "/home/Redhat/Log/{{ item.item }}.log"
        state: touch
        mode: '0644'
      loop: "{{ service_status.results }}"
      loop_control:
        label: "{{ item.item }}"
      delegate_to: localhost

    - name: Start the services if they are not running
      ansible.windows.win_service:
        name: "{{ item.item }}"
        state: started
      when: item.state != 'running'
      register: service_log
      loop: "{{ service_status.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Log service status when already running to individual files
      ansible.builtin.lineinfile:
        path: "/home/Redhat/Log/{{ item.item }}.log"
        line: "{{ ansible_date_time.iso8601 }} {{ item.item }} service is already running"
        insertafter: '^.*$'
      when: item.state == 'running'
      loop: "{{ service_status.results }}"
      loop_control:
        label: "{{ item.item }}"
      delegate_to: localhost

    - name: Log service status when started to individual files
      ansible.builtin.lineinfile:
        path: "/home/Redhat/Log/{{ item.item }}.log"
        line: "{{ ansible_date_time.iso8601 }} {{ item.item }} service started now"
        insertafter: '^.*$'
      when: item.state != 'running'
      loop: "{{ service_status.results }}"
      loop_control:
          label: "{{ item.item }}"
      delegate_to: localhost