HPC Certificate (Installed)
.NET 4.8 Framework with latest patches (Installed)
SQL Server Management Studio 20 (Installed)
SQL CMD 2022 (Installed)
PowerShell Installation Scripts (Installed)
Autosys and NDM binaries
HPC Pack 2019 Update 2 installation binary
