name: Build Image and deploy VM
 
on:
  push:
    branches:
      #- main
       - dev
jobs:
  packer:
    name: Build packer and Publish Image to SIG
    runs-on: [self-hosted,test]
    env:
      ROOT_PATH : '${{github.workspace}}/windows'
 
    permissions:
      id-token: write
      contents: read
 
